"use client";

import { useState } from "react";
import { MedicalRecord } from "@/data/mockRecords";
import Toast from "./Toast";

export default function DownloadButton({ record }: { record: MedicalRecord }) {
  const [showToast, setShowToast] = useState(false);

  const handleDownload = () => {
    const today = new Date().toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    const medicationsSection = record.medications
      .map(
        (m) =>
          `  • ${m.name} ${m.dosage} — ${m.frequency}\n    Context: "${m.relevantText}"\n    Confidence: ${m.confidence}`
      )
      .join("\n\n");

    const diagnosesSection = record.diagnoses
      .map(
        (d) =>
          `  • ${d.name} (ICD-10: ${d.icdCode})\n    Context: "${d.relevantText}"\n    Date: ${d.dateContext}`
      )
      .join("\n\n");

    const content = `================================================================================
MEDPARSE — DOCUMENT REVIEW FORM
================================================================================

Review Date:     ${today}
Document ID:     ${record.id.toUpperCase()}

PATIENT INFORMATION
--------------------------------------------------------------------------------
Patient Name:    ${record.patientName}
Date of Birth:   ${record.dateOfBirth}

DOCUMENT INFORMATION
--------------------------------------------------------------------------------
Document Type:   ${record.documentType}
Document Date:   ${record.documentDate}
Reviewed Date:   ${record.reviewedDate || today}
Provider:        ${record.provider}
Facility:        ${record.facility}
Review Status:   ${record.status}

IDENTIFIED MEDICATIONS (${record.medications.length})
--------------------------------------------------------------------------------
${medicationsSection}

IDENTIFIED DIAGNOSES (${record.diagnoses.length})
--------------------------------------------------------------------------------
${diagnosesSection}

EXTRACTED MEDICAL TEXT
--------------------------------------------------------------------------------
${record.extractedText}

================================================================================
Generated by MedParse AI Document Review System
This document is a prototype output for demonstration purposes only.
================================================================================
`;

    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `MedParse_Review_${record.patientName.replace(/\s+/g, "_")}_${record.documentDate}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setShowToast(true);
  };

  return (
    <>
      <button
        onClick={handleDownload}
        className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white text-sm font-medium px-5 py-2.5 rounded-lg transition-colors shadow-sm"
      >
        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
            d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
        </svg>
        Download Review Form
      </button>
      {showToast && (
        <Toast
          message="Review form downloaded successfully"
          type="success"
          onDismiss={() => setShowToast(false)}
        />
      )}
    </>
  );
}
